apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fullnameOverride | default "vite-app" }}-svc
spec:
  selector:
    app: {{ .Values.appLabels.app }}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.containerPort }}
