apiVersion: v1
kind: Service
metadata:
  name: vite-app-service
spec:
  selector:
    app: vite-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # Exposes port 80
      targetPort: 3000 # Your Vite app inside the container
