apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vite-app
  template:
    metadata:
      labels:
        app: vite-app
    spec:
      containers:
        - name: vite-app
          image: vite-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
